apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: superpod-ssh
spec:
  description: A Task for interact remotely via ssh
  params:
    - default: /root
      description: |
        Absolute path to the user home directory.
      name: USER_HOME
      type: string
    - default: 'false'
      description: |
        Log the executed commands.
      name: VERBOSE
      type: string
    - default: 'true'
      description: |
        Sets the global `http.sslVerify` value, `false` is not advised unless
        you trust the remote repository.
      name: SSL_VERIFY
      type: string
    - default: user
      description: |
        User to be used for ssh connection
      name: SSH_USER
      type: string
    - default: remote
      description: |
        Host to connect to
      name: SSH_HOST
      type: string
    - default: ""
      description: |
        Remote directory where the image is copied to
      name: SSH_DIRECTORY
      type: string
    - name: IMAGE
      type: string
      default: superpod.sqfs
      description: |
        Image in sqfs formatto run
    - default: 1
      description: |
        Number of nodes to be used for the task.
      name: NODES
      type: string
    - name: WORKERS
      description: |
        Worker nodes to be used for the task.
      type: string
    - default: 1
      description: |
        Number of GPUs to be used for the task.
      name: GPUS
      type: string
    - default: myjob
      description: |
        Name of the job to be used for the task.
      name: JOB_NAME
      type: string
    - default: 02:00:00
      description: |
        Time limit for the job to be used for the task.
      name: TIME
      type: string
    - default: "echo 'Hello World'"
      description: |
        Command to be executed in the remote server.
      name: COMMAND
      type: string
  results:
    - description: |
        A simple result
      name: simpleresult
      type: string
  stepTemplate:
    computeResources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    env:
      - name: PARAMS_USER_HOME
        value: $(params.USER_HOME)
      - name: SSH_USER
        value: $(params.SSH_USER)
      - name: SSH_HOST
        value: $(params.SSH_HOST)
      - name: SSH_DIRECTORY
        value: $(params.SSH_DIRECTORY)
      - name: PARAMS_NODES
        value: $(params.NODES)
      - name: PARAMS_IMAGE
        value: $(params.IMAGE)
      - name: PARAMS_WORKERS
        value: $(params.WORKERS)
      - name: PARAMS_GPUS
        value: $(params.GPUS)
      - name: PARAMS_JOB_NAME
        value: $(params.JOB_NAME)
      - name: PARAMS_TIME
        value: $(params.TIME)
      - name: PARAMS_COMMAND
        value: $(params.COMMAND)
      - name: WORKSPACES_OUTPUT_PATH
        value: $(workspaces.output.path)
      - name: PARAMS_VERBOSE
        value: $(params.VERBOSE)
      - name: WORKSPACES_SSH_DIRECTORY_BOUND
        value: $(workspaces.ssh-directory.bound)
      - name: WORKSPACES_SSH_DIRECTORY_PATH
        value: $(workspaces.ssh-directory.path)
      - name: WORKSPACES_IMAGEDIRECTORY_BOUND
        value: $(workspaces.imagedirectory.bound)
      - name: WORKSPACES_IMAGEDIRECTORY_PATH
        value: $(workspaces.imagedirectory.path)
  steps:
    - name: prepare-and-run
      image: 'registry.mlops.software.bl.platform:8443/copy-model/ubi9-ssh:latest'
      script: |
        set -e
        printf '%s' "IyEvdXNyL2Jpbi9lbnYgc2gKCmV4cG9ydCBQQVJBTVNfVVJMPSIke1BBUkFNU19VUkw6LX0iCmV4cG9ydCBQQVJBTVNfUkVWSVNJT049IiR7UEFSQU1TX1JFVklTSU9OOi19IgpleHBvcnQgUEFSQU1TX1JFRlNQRUM9IiR7UEFSQU1TX1JFRlNQRUM6LX0iCmV4cG9ydCBQQVJBTVNfU1VCTU9EVUxFUz0iJHtQQVJBTVNfU1VCTU9EVUxFUzotfSIKZXhwb3J0IFBBUkFNU19ERVBUSD0iJHtQQVJBTVNfREVQVEg6LX0iCmV4cG9ydCBQQVJBTVNfU1NMX1ZFUklGWT0iJHtQQVJBTVNfU1NMX1ZFUklGWTotfSIKZXhwb3J0IFBBUkFNU19DUlRfRklMRU5BTUU9IiR7UEFSQU1TX0NSVF9GSUxFTkFNRTotfSIKZXhwb3J0IFBBUkFNU19TVUJESVJFQ1RPUlk9IiR7UEFSQU1TX1NVQkRJUkVDVE9SWTotfSIKZXhwb3J0IFBBUkFNU19TUEFSU0VfQ0hFQ0tPVVRfRElSRUNUT1JJRVM9IiR7UEFSQU1TX1NQQVJTRV9DSEVDS09VVF9ESVJFQ1RPUklFUzotfSIKZXhwb3J0IFBBUkFNU19ERUxFVEVfRVhJU1RJTkc9IiR7UEFSQU1TX0RFTEVURV9FWElTVElORzotfSIKZXhwb3J0IFBBUkFNU19IVFRQX1BST1hZPSIke1BBUkFNU19IVFRQX1BST1hZOi19IgpleHBvcnQgUEFSQU1TX0hUVFBTX1BST1hZPSIke1BBUkFNU19IVFRQU19QUk9YWTotfSIKZXhwb3J0IFBBUkFNU19OT19QUk9YWT0iJHtQQVJBTVNfTk9fUFJPWFk6LX0iCmV4cG9ydCBQQVJBTVNfVkVSQk9TRT0iJHtQQVJBTVNfVkVSQk9TRTotfSIKZXhwb3J0IFBBUkFNU19VU0VSX0hPTUU9IiR7UEFSQU1TX1VTRVJfSE9NRTotfSIKZXhwb3J0IFBBUkFNU19HSVRfVVNFUl9FTUFJTD0iJHtQQVJBTVNfR0lUX1VTRVJfRU1BSUw6LX0iCmV4cG9ydCBQQVJBTVNfR0lUX1VTRVJfTkFNRT0iJHtQQVJBTVNfR0lUX1VTRVJfTkFNRTotfSIKZXhwb3J0IFBBUkFNU19HSVRfU0NSSVBUPSIke1BBUkFNU19HSVRfU0NSSVBUOi19IgoKZXhwb3J0IFdPUktTUEFDRVNfT1VUUFVUX0JPVU5EPSIke1dPUktTUEFDRVNfT1VUUFVUX0JPVU5EOi19IgpleHBvcnQgV09SS1NQQUNFU19PVVRQVVRfUEFUSD0iJHtXT1JLU1BBQ0VTX09VVFBVVF9QQVRIOi19IgpleHBvcnQgV09SS1NQQUNFU19TU0hfRElSRUNUT1JZX0JPVU5EPSIke1dPUktTUEFDRVNfU1NIX0RJUkVDVE9SWV9CT1VORDotfSIKZXhwb3J0IFdPUktTUEFDRVNfU1NIX0RJUkVDVE9SWV9QQVRIPSIke1dPUktTUEFDRVNfU1NIX0RJUkVDVE9SWV9QQVRIOi19IgpleHBvcnQgV09SS1NQQUNFU19CQVNJQ19BVVRIX0JPVU5EPSIke1dPUktTUEFDRVNfQkFTSUNfQVVUSF9CT1VORDotfSIKZXhwb3J0IFdPUktTUEFDRVNfQkFTSUNfQVVUSF9QQVRIPSIke1dPUktTUEFDRVNfQkFTSUNfQVVUSF9QQVRIOi19IgoKZXhwb3J0IFJFU1VMVFNfQ09NTUlUVEVSX0RBVEVfUEFUSD0iJHtSRVNVTFRTX0NPTU1JVFRFUl9EQVRFX1BBVEg6LX0iCmV4cG9ydCBSRVNVTFRTX0NPTU1JVF9QQVRIPSIke1JFU1VMVFNfQ09NTUlUX1BBVEg6LX0iCmV4cG9ydCBSRVNVTFRTX1VSTF9QQVRIPSIke1JFU1VMVFNfVVJMX1BBVEg6LX0iCgojCiMgRnVuY3Rpb25zCiMKCmZhaWwoKSB7CiAgICBlY2hvICJFUlJPUjogJHtAfSIgMT4mMgogICAgZXhpdCAxCn0KCnBoYXNlKCkgewogICAgZWNobyAiLS0tPiBQaGFzZTogJHtAfS4uLiIKfQoKIyBJbnNwZWN0IHRoZSBlbnZpcm9ubWVudCB2YXJpYWJsZXMgdG8gYXNzZXJ0IHRoZSBtaW5pbXVtIGNvbmZpZ3VyYXRpb24gaXMgaW5mb3JtZWQuCmFzc2VydF9yZXF1aXJlZF9jb25maWd1cmF0aW9uX29yX2ZhaWwoKSB7CiAgICBbWyAteiAiJHtQQVJBTVNfVVJMfSIgICYmICAteiAiJHtQQVJBTVNfR0lUX1NDUklQVH0iIF1dICYmCiAgICAgICAgZmFpbCAiUGFyYW1ldGVyIFVSTCBvciBTQ1JJUFQgbXVzdCBiZSBzZXQhIgoKICAgIFtbIC16ICIke1dPUktTUEFDRVNfUk9PVF9QQVRIfSIgXV0gJiYKICAgICAgICBmYWlsICJSb290IFdvcmtzcGFjZSBpcyBub3Qgc2V0ISIKCiAgICBbWyAhIC1kICIke1dPUktTUEFDRVNfUk9PVF9QQVRIfSIgXV0gJiYKICAgICAgICBmYWlsICJSb290IFdvcmtzcGFjZSBkaXJlY3Rvcnkgbm90IGZvdW5kISIKICAgIHJldHVybiAwCn0KCiMgQ29weSB0aGUgZmlsZSBpbnRvIHRoZSBkZXN0aW5hdGlvbiwgY2hlY2tpbmcgaWYgdGhlIHNvdXJjZSBleGlzdHMuCmNvcHlfb3JfZmFpbCgpIHsKICAgIGxvY2FsIF9tb2RlPSIkezF9IgogICAgbG9jYWwgX3NyYz0iJHsyfSIKICAgIGxvY2FsIF9kc3Q9IiR7M30iCgogICAgaWYgW1sgISAtZiAiJHtfc3JjfSIgJiYgISAtZCAiJHtfc3JjfSIgXV07IHRoZW4KICAgICAgICBmYWlsICJTb3VyY2UgZmlsZS9kaXJlY3RvcnkgaXMgbm90IGZvdW5kIGF0ICcke19zcmN9JyIKICAgIGZpCgogICAgaWYgW1sgLWQgIiR7X3NyY30iIF1dOyB0aGVuCiAgICAgICAgY3AgLVJ2ICR7X3NyY30gJHtfZHN0fQogICAgICAgIGNobW9kIC12ICR7X21vZGV9ICR7X2RzdH0KICAgIGVsc2UKICAgICAgICBpbnN0YWxsIC0tdmVyYm9zZSAtLW1vZGU9JHtfbW9kZX0gJHtfc3JjfSAke19kc3R9CiAgICBmaQp9CgojIERlbGV0ZSBhbnkgZXhpc3RpbmcgY29udGVudHMgb2YgdGhlIHJlcG8gZGlyZWN0b3J5IGlmIGl0IGV4aXN0cy4gV2UgZG9uJ3QganVzdCAicm0gLXJmIDxkaXI+IgojIGJlY2F1c2UgbWlnaHQgYmUgIi8iIG9yIHRoZSByb290IG9mIGEgbW91bnRlZCB2b2x1bWUuCmNsZWFuX2RpcigpIHsKICAgIGxvY2FsIF9kaXI9IiR7MX0iCgogICAgW1sgISAtZCAiJHtfZGlyfSIgXV0gJiYKICAgICAgICByZXR1cm4gMAoKICAgICMgRGVsZXRlIG5vbi1oaWRkZW4gZmlsZXMgYW5kIGRpcmVjdG9yaWVzCiAgICBybSAtcmZ2ICR7X2Rpcjo/fS8qCiAgICAjIERlbGV0ZSBmaWxlcyBhbmQgZGlyZWN0b3JpZXMgc3RhcnRpbmcgd2l0aCAuIGJ1dCBleGNsdWRpbmcgLi4KICAgIHJtIC1yZnYgJHtfZGlyfS8uWyEuXSoKICAgICMgRGVsZXRlIGZpbGVzIGFuZCBkaXJlY3RvcmllcyBzdGFydGluZyB3aXRoIC4uIHBsdXMgYW55IG90aGVyIGNoYXJhY3RlcgogICAgcm0gLXJmdiAke19kaXJ9Ly4uPyoKfQoKIwojIFNldHRpbmdzCiMKCiMgbWFraW5nIHRoZSBzaGVsbCB2ZXJib3NlIHdoZW4gdGhlIHBhcmFtdGVyIGlzIHNldApbWyAiJHtQQVJBTVNfVkVSQk9TRX0iID09ICJ0cnVlIiBdXSAmJiBzZXQgLXgKCnJldHVybiAwCg==" |base64 -d >"/scripts/common.sh"
        printf '%s' "IyEvdXNyL2Jpbi9lbnYgc2gKIwojIFNldHMgdXAgdGhlIGJhc2ljIGFuZCBTU0ggYXV0aGVudGljYXRpb24gYmFzZWQgb24gaW5mb3JtZWQgd29ya3NwYWNlcywgYXMgd2VsbCBhcyBjbGVhbmluZyB1cCB0aGUKIyBwcmV2aW91cyBnaXQtY2xvbmUgc3RhbGUgZGF0YS4KIwoKc2V0IC1ldQoKc291cmNlICQoQ0RQQVRIPSBjZCAtLSAiJChkaXJuYW1lIC0tICR7MH0pIiAmJiBwd2QpL2NvbW1vbi5zaAoKIyMjIyBhc3NlcnRfcmVxdWlyZWRfY29uZmlndXJhdGlvbl9vcl9mYWlsCgpwaGFzZSAiUHJlcGFyaW5nIHRoZSBmaWxlc3lzdGVtIgoKaWYgW1sgIiR7V09SS1NQQUNFU19CQVNJQ19BVVRIX0JPVU5EfSIgPT0gInRydWUiIF1dOyB0aGVuCglwaGFzZSAiQ29uZmlndXJpbmcgR2l0IGF1dGhlbnRpY2F0aW9uIHdpdGggJ2Jhc2ljLWF1dGgnIFdvcmtzcGFjZSBmaWxlcyIKCglmb3IgZiBpbiAuZ2l0LWNyZWRlbnRpYWxzIC5naXRjb25maWc7IGRvCgkJc3JjPSIke1dPUktTUEFDRVNfQkFTSUNfQVVUSF9QQVRIfS8ke2Z9IgoJCXBoYXNlICJDb3B5aW5nICcke3NyY30nIHRvICcke1BBUkFNU19VU0VSX0hPTUV9JyIKCQljb3B5X29yX2ZhaWwgNDAwICR7c3JjfSAiJHtQQVJBTVNfVVNFUl9IT01FfS8iCglkb25lCmZpCgppZiBbWyAiJHtXT1JLU1BBQ0VTX1NTSF9ESVJFQ1RPUllfQk9VTkR9IiA9PSAidHJ1ZSIgXV07IHRoZW4KCXBoYXNlICJDb3B5aW5nICcuc3NoJyBmcm9tIHNzaC1kaXJlY3Rvcnkgd29ya3NwYWNlICgnJHtXT1JLU1BBQ0VTX1NTSF9ESVJFQ1RPUllfUEFUSH0nKSIKCglkb3Rfc3NoPSIke1BBUkFNU19VU0VSX0hPTUV9Ly5zc2giCgljb3B5X29yX2ZhaWwgNzAwICR7V09SS1NQQUNFU19TU0hfRElSRUNUT1JZX1BBVEh9ICR7ZG90X3NzaH0KCWNobW9kIC1SdiA0MDAgJHtkb3Rfc3NofS8qCmZpCgoKZXhpdCAwCg==" |base64 -d >"/scripts/prepare.sh"
        printt '%s' "IyEvdXNyL2Jpbi9lbnYgc2gKCiMKIyBJbWFnZSBpcyBhbHJlYWR5IGNyZWF0ZWQKIyAke1BBUkFNU19JTUFHRX0KIwoKc2NwICR7UEFSQU1TX0lNQUdFfSAke1NTSF9VU0VSfUAke1NTSF9IT1NUfToke1NTSF9ESVJFQ1RPUll9CgpjYXQgPiBkZXBsb3kuc2ggPDxFT0YKIyBOb3cgd2UgbmVlZWQgdG8gY3JlYXRlIGEgc2NyaXB0IHRvIGV4ZWN1dGUgdGhlIGltYWdlCgojIENvbmZpZ3VyYWNpw7NuIGRlIHBhcsOhbWV0cm9zCk5PREVTPSR7UEFSQU1TX05PREVTfSAgICAgICAgICAgICAjIE7Dum1lcm8gZGUgbm9kb3MKVEFTS1M9JHtQQVJBTVNfVEFTS1N9ICAgICAgICAgICAgICMgTsO6bWVybyBkZSB0YXJlYXMKUEFSVElUSU9OPSJpbnRlcmFjdGl2ZSIgICAgICAgICAgICMgTm9tYnJlIGRlIGxhIHBhcnRpY2nDs24gLT4gaW50ZXJhY3RpdmUgKG1heCAyIGTDrWFzKSwgYmF0Y2ggKG1heCAzMCBkw61hcykKV09SS0VSPSIke1BBUkFNU19XT1JLRVJTfSIgICAgICAgICMgTm9tYnJlIGRlbCBub2RvIGRlIHRyYWJham8KR1BVUz0ke1BBUkFNU19HUFVTfSAgICAgICAgICAgICAgICMgTsO6bWVybyBkZSBHUFVzCkpPQl9OQU1FPSIke1BBUkFNU19KT0JfTkFNRX0iICAgICAjIE5vbWJyZSBkZWwgdHJhYmFqbwpUSU1FPSIke1BBUkFNU19USU1FfSIgICAgICAgICAgICAgIyBMw61taXRlIGRlIHRpZW1wbyAtPiBlLmcuIDQgZMOtYXMgOCBob3JhcyAwNDowODowMDowMApDT01NQU5EPSIke1BBUkFNU19DT01NQU5EfSIKCiMgRWplY3V0YXIgZWwgY29tYW5kbyBzcnVuCnNydW4gLUsgXAogICAgLS1jb250YWluZXItbW91bnRzPS9ob21lLyR7U1NIX1VTRVJ9Oi9ob21lLyR7U1NIX1VTRVJ9IFwKICAgIC0tY29udGFpbmVyLW1vdW50cz0vZXRjL3NzaC9ob3N0KjovZXRjL3NzaC8gXAogICAgLS1uby1jb250YWluZXItcmVtYXAtcm9vdCBcCiAgICAtLWNvbnRhaW5lci13b3JrZGlyPSQocHdkKSBcCiAgICAtLWNvbnRhaW5lci1pbWFnZT0iJHtQQVJBTVNfSU1BR0V9IiBcCiAgICAtLW50YXNrcz0iXCRUQVNLUyIgXAogICAgLS1ub2Rlcz0iXCROT0RFUyIgXAogICAgLS1wYXJ0aXRpb24gIlwkUEFSVElUSU9OIiBcCiAgICAtLW5vZGVsaXN0ICJcJFdPUktFUiIgXAogICAgLS1ncHVzPSJcJEdQVVMiIFwKICAgIC0tam9iLW5hbWUgIlwkSk9CX05BTUUiIFwKICAgIC0tdGltZSAiXCRUSU1FIiBcCiAgICAtLXB0eSAvYmluL2Jhc2ggLWMgIlwke0NPTU1BTkR9IgpFT0YKCmNobW9kICt4IGRlcGxveS5zaAoKIyBjb3B5IHRvIHJlbW90ZSBzZXJ2ZXIKc2NwIGRlcGxveS5zaCAke1NTSF9VU0VSfUAke1NTSF9IT1NUfToke1NTSF9ESVJ9Cgpzc2ggJHtTU0hfVVNFUn1AJHtTU0hfSE9TVH0gImNobW9kIGEreCAuL2RlcGxveS5zaCAmJiAuL2RlcGxveS5zaCIK" |base64 -d >"/scripts/remote.sh"
        chmod +x /scripts/*.sh;echo "Running Script /scripts/prepare.sh";
            /scripts/prepare.sh;
        echo "Running Script /scripts/remote.sh";
            /scripts/remote.sh;
      volumeMounts:
        - mountPath: /scripts
          name: scripts-dir
  volumes:
    - emptyDir: {}
      name: scripts-dir
  workspaces:
    - description: |
        A `.ssh` directory with private key, `known_hosts`, `config`, etc.
        Copied to the user's home, in order to
        server as authentication mechanism binding a Secret to this Workspace is
        strongly recommended over other volume types.
      name: ssh-directory
      optional: true
    - description: |
        A directory for storing the .sqsh image.
      name: imagedirectory
