apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: superpod-ssh
spec:
  description: A Task for interact remotely via ssh
  params:
    - default: /root
      description: |
        Absolute path to the user home directory.
      name: USER_HOME
      type: string
    - default: 'false'
      description: |
        Log the executed commands.
      name: VERBOSE
      type: string
    - default: 'true'
      description: |
        Sets the global `http.sslVerify` value, `false` is not advised unless
        you trust the remote repository.
      name: SSL_VERIFY
      type: string
    - default: user
      description: |
        User to be used for ssh connection
      name: SSH_USER
      type: string
    - default: remote
      description: |
        Host to connect to
      name: SSH_HOST
      type: string
    - default: ""
      description: |
        Remote directory where the image is copied to
      name: SSH_DIRECTORY
      type: string
    - name: IMAGE
      type: string
      default: superpod.sqfs
      description: |
        Image in sqfs formatto run
    - default: 1
      description: |
        Number of nodes to be used for the task.
      name: NODES
      type: string
    - name: TASKS
      description: |
        Number of tasks to be used for the task.
      type: string
      default: 1
    - name: WORKERS
      description: |
        Worker nodes to be used for the task.
      type: string
    - default: 1
      description: |
        Number of GPUs to be used for the task.
      name: GPUS
      type: string
    - default: myjob
      description: |
        Name of the job to be used for the task.
      name: JOB_NAME
      type: string
    - default: 02:00:00
      description: |
        Time limit for the job to be used for the task.
      name: TIME
      type: string
    - default: "echo 'Hello World'"
      description: |
        Command to be executed in the remote server.
      name: COMMAND
      type: string
  results:
    - description: |
        A simple result
      name: simpleresult
      type: string
  stepTemplate:
    computeResources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    env:
      - name: PARAMS_USER_HOME
        value: $(params.USER_HOME)
      - name: SSH_USER
        value: $(params.SSH_USER)
      - name: SSH_HOST
        value: $(params.SSH_HOST)
      - name: SSH_DIRECTORY
        value: $(params.SSH_DIRECTORY)
      - name: PARAMS_NODES
        value: $(params.NODES)
      - name: PARAMS_IMAGE
        value: $(params.IMAGE)
      - name: PARAMS_TASKS
        value: $(params.TASKS)
      - name: PARAMS_WORKERS
        value: $(params.WORKERS)
      - name: PARAMS_GPUS
        value: $(params.GPUS)
      - name: PARAMS_JOB_NAME
        value: $(params.JOB_NAME)
      - name: PARAMS_TIME
        value: $(params.TIME)
      - name: PARAMS_COMMAND
        value: $(params.COMMAND)
      - name: WORKSPACES_OUTPUT_PATH
        value: $(workspaces.output.path)
      - name: PARAMS_VERBOSE
        value: $(params.VERBOSE)
      - name: WORKSPACES_SSH_DIRECTORY_BOUND
        value: $(workspaces.ssh-directory.bound)
      - name: WORKSPACES_SSH_DIRECTORY_PATH
        value: $(workspaces.ssh-directory.path)
      - name: WORKSPACES_IMAGEDIRECTORY_BOUND
        value: $(workspaces.imagedirectory.bound)
      - name: WORKSPACES_IMAGEDIRECTORY_PATH
        value: $(workspaces.imagedirectory.path)
  steps:
    - name: prepare-and-run
      image: 'registry.mlops.software.bl.platform:8443/copy-model/ubi9-ssh:latest'
      script: |
        set -e
        printf '%s' "IyEvdXNyL2Jpbi9lbnYgc2gKCmV4cG9ydCBQQVJBTVNfVVJMPSIke1BBUkFNU19VUkw6LX0iCmV4cG9ydCBQQVJBTVNfUkVWSVNJT049IiR7UEFSQU1TX1JFVklTSU9OOi19IgpleHBvcnQgUEFSQU1TX1JFRlNQRUM9IiR7UEFSQU1TX1JFRlNQRUM6LX0iCmV4cG9ydCBQQVJBTVNfU1VCTU9EVUxFUz0iJHtQQVJBTVNfU1VCTU9EVUxFUzotfSIKZXhwb3J0IFBBUkFNU19ERVBUSD0iJHtQQVJBTVNfREVQVEg6LX0iCmV4cG9ydCBQQVJBTVNfU1NMX1ZFUklGWT0iJHtQQVJBTVNfU1NMX1ZFUklGWTotfSIKZXhwb3J0IFBBUkFNU19DUlRfRklMRU5BTUU9IiR7UEFSQU1TX0NSVF9GSUxFTkFNRTotfSIKZXhwb3J0IFBBUkFNU19TVUJESVJFQ1RPUlk9IiR7UEFSQU1TX1NVQkRJUkVDVE9SWTotfSIKZXhwb3J0IFBBUkFNU19TUEFSU0VfQ0hFQ0tPVVRfRElSRUNUT1JJRVM9IiR7UEFSQU1TX1NQQVJTRV9DSEVDS09VVF9ESVJFQ1RPUklFUzotfSIKZXhwb3J0IFBBUkFNU19ERUxFVEVfRVhJU1RJTkc9IiR7UEFSQU1TX0RFTEVURV9FWElTVElORzotfSIKZXhwb3J0IFBBUkFNU19IVFRQX1BST1hZPSIke1BBUkFNU19IVFRQX1BST1hZOi19IgpleHBvcnQgUEFSQU1TX0hUVFBTX1BST1hZPSIke1BBUkFNU19IVFRQU19QUk9YWTotfSIKZXhwb3J0IFBBUkFNU19OT19QUk9YWT0iJHtQQVJBTVNfTk9fUFJPWFk6LX0iCmV4cG9ydCBQQVJBTVNfVkVSQk9TRT0iJHtQQVJBTVNfVkVSQk9TRTotfSIKZXhwb3J0IFBBUkFNU19VU0VSX0hPTUU9IiR7UEFSQU1TX1VTRVJfSE9NRTotfSIKZXhwb3J0IFBBUkFNU19HSVRfVVNFUl9FTUFJTD0iJHtQQVJBTVNfR0lUX1VTRVJfRU1BSUw6LX0iCmV4cG9ydCBQQVJBTVNfR0lUX1VTRVJfTkFNRT0iJHtQQVJBTVNfR0lUX1VTRVJfTkFNRTotfSIKZXhwb3J0IFBBUkFNU19HSVRfU0NSSVBUPSIke1BBUkFNU19HSVRfU0NSSVBUOi19IgoKZXhwb3J0IFdPUktTUEFDRVNfT1VUUFVUX0JPVU5EPSIke1dPUktTUEFDRVNfT1VUUFVUX0JPVU5EOi19IgpleHBvcnQgV09SS1NQQUNFU19PVVRQVVRfUEFUSD0iJHtXT1JLU1BBQ0VTX09VVFBVVF9QQVRIOi19IgpleHBvcnQgV09SS1NQQUNFU19TU0hfRElSRUNUT1JZX0JPVU5EPSIke1dPUktTUEFDRVNfU1NIX0RJUkVDVE9SWV9CT1VORDotfSIKZXhwb3J0IFdPUktTUEFDRVNfU1NIX0RJUkVDVE9SWV9QQVRIPSIke1dPUktTUEFDRVNfU1NIX0RJUkVDVE9SWV9QQVRIOi19IgpleHBvcnQgV09SS1NQQUNFU19CQVNJQ19BVVRIX0JPVU5EPSIke1dPUktTUEFDRVNfQkFTSUNfQVVUSF9CT1VORDotfSIKZXhwb3J0IFdPUktTUEFDRVNfQkFTSUNfQVVUSF9QQVRIPSIke1dPUktTUEFDRVNfQkFTSUNfQVVUSF9QQVRIOi19IgoKZXhwb3J0IFJFU1VMVFNfQ09NTUlUVEVSX0RBVEVfUEFUSD0iJHtSRVNVTFRTX0NPTU1JVFRFUl9EQVRFX1BBVEg6LX0iCmV4cG9ydCBSRVNVTFRTX0NPTU1JVF9QQVRIPSIke1JFU1VMVFNfQ09NTUlUX1BBVEg6LX0iCmV4cG9ydCBSRVNVTFRTX1VSTF9QQVRIPSIke1JFU1VMVFNfVVJMX1BBVEg6LX0iCgpkZWNsYXJlIC1yeCBQQVJBTVNfSU1BR0U9IiR7UEFSQU1TX0lNQUdFOi19IgpkZWNsYXJlIC1yeCBQQVJBTVNfVExTX1ZFUklGWT0iJHtQQVJBTVNfVExTX1ZFUklGWTotfSIKZGVjbGFyZSAtcnggUEFSQU1TX1ZFUkJPU0U9IiR7UEFSQU1TX1ZFUkJPU0U6LX0iCgpkZWNsYXJlIC1yeCBXT1JLU1BBQ0VTX0lNQUdFRElSRUNUT1JZX1BBVEg9IiR7V09SS1NQQUNFU19JTUFHRURJUkVDVE9SWV9QQVRIOi19IgpkZWNsYXJlIC1yeCBXT1JLU1BBQ0VTX0lNQUdFRElSRUNUT1JZX0JPVU5EPSIke1dPUktTUEFDRVNfSU1BR0VESVJFQ1RPUllfQk9VTkQ6LX0iCgojCiMgRnVuY3Rpb25zCiMKCmZhaWwoKSB7CiAgICBlY2hvICJFUlJPUjogJHtAfSIgMT4mMgogICAgZXhpdCAxCn0KCnBoYXNlKCkgewogICAgZWNobyAiLS0tPiBQaGFzZTogJHtAfS4uLiIKfQoKIyBJbnNwZWN0IHRoZSBlbnZpcm9ubWVudCB2YXJpYWJsZXMgdG8gYXNzZXJ0IHRoZSBtaW5pbXVtIGNvbmZpZ3VyYXRpb24gaXMgaW5mb3JtZWQuCmFzc2VydF9yZXF1aXJlZF9jb25maWd1cmF0aW9uX29yX2ZhaWwoKSB7CiAgICBbWyAteiAiJHtQQVJBTVNfVVJMfSIgICYmICAteiAiJHtQQVJBTVNfR0lUX1NDUklQVH0iIF1dICYmCiAgICAgICAgZmFpbCAiUGFyYW1ldGVyIFVSTCBvciBTQ1JJUFQgbXVzdCBiZSBzZXQhIgoKICAgIFtbIC16ICIke1dPUktTUEFDRVNfUk9PVF9QQVRIfSIgXV0gJiYKICAgICAgICBmYWlsICJSb290IFdvcmtzcGFjZSBpcyBub3Qgc2V0ISIKCiAgICBbWyAhIC1kICIke1dPUktTUEFDRVNfUk9PVF9QQVRIfSIgXV0gJiYKICAgICAgICBmYWlsICJSb290IFdvcmtzcGFjZSBkaXJlY3Rvcnkgbm90IGZvdW5kISIKICAgIHJldHVybiAwCn0KCgojIENvcHkgdGhlIGZpbGUgaW50byB0aGUgZGVzdGluYXRpb24sIGNoZWNraW5nIGlmIHRoZSBzb3VyY2UgZXhpc3RzLgpjb3B5X29yX2ZhaWwoKSB7CiAgICBsb2NhbCBfbW9kZT0iJHsxfSIKICAgIGxvY2FsIF9zcmM9IiR7Mn0iCiAgICBsb2NhbCBfZHN0PSIkezN9IgoKICAgIGlmIFtbICEgLWYgIiR7X3NyY30iICYmICEgLWQgIiR7X3NyY30iIF1dOyB0aGVuCiAgICAgICAgZmFpbCAiU291cmNlIGZpbGUvZGlyZWN0b3J5IGlzIG5vdCBmb3VuZCBhdCAnJHtfc3JjfSciCiAgICBmaQoKICAgIGlmIFtbIC1kICIke19zcmN9IiBdXTsgdGhlbgogICAgICAgIGNwIC1SdiAke19zcmN9ICR7X2RzdH0KICAgICAgICBjaG1vZCAtdiAke19tb2RlfSAke19kc3R9CiAgICBlbHNlCiAgICAgICAgaW5zdGFsbCAtLXZlcmJvc2UgLS1tb2RlPSR7X21vZGV9ICR7X3NyY30gJHtfZHN0fQogICAgZmkKfQoKIyBEZWxldGUgYW55IGV4aXN0aW5nIGNvbnRlbnRzIG9mIHRoZSByZXBvIGRpcmVjdG9yeSBpZiBpdCBleGlzdHMuIFdlIGRvbid0IGp1c3QgInJtIC1yZiA8ZGlyPiIKIyBiZWNhdXNlIG1pZ2h0IGJlICIvIiBvciB0aGUgcm9vdCBvZiBhIG1vdW50ZWQgdm9sdW1lLgpjbGVhbl9kaXIoKSB7CiAgICBsb2NhbCBfZGlyPSIkezF9IgoKICAgIFtbICEgLWQgIiR7X2Rpcn0iIF1dICYmCiAgICAgICAgcmV0dXJuIDAKCiAgICAjIERlbGV0ZSBub24taGlkZGVuIGZpbGVzIGFuZCBkaXJlY3RvcmllcwogICAgcm0gLXJmdiAke19kaXI6P30vKgogICAgIyBEZWxldGUgZmlsZXMgYW5kIGRpcmVjdG9yaWVzIHN0YXJ0aW5nIHdpdGggLiBidXQgZXhjbHVkaW5nIC4uCiAgICBybSAtcmZ2ICR7X2Rpcn0vLlshLl0qCiAgICAjIERlbGV0ZSBmaWxlcyBhbmQgZGlyZWN0b3JpZXMgc3RhcnRpbmcgd2l0aCAuLiBwbHVzIGFueSBvdGhlciBjaGFyYWN0ZXIKICAgIHJtIC1yZnYgJHtfZGlyfS8uLj8qCn0KCiMKIyBTZXR0aW5ncwojCgojIG1ha2luZyB0aGUgc2hlbGwgdmVyYm9zZSB3aGVuIHRoZSBwYXJhbXRlciBpcyBzZXQKW1sgIiR7UEFSQU1TX1ZFUkJPU0V9IiA9PSAidHJ1ZSIgXV0gJiYgc2V0IC14CgpyZXR1cm4gMA==" |base64 -d >"/scripts/common.sh"
        printf '%s' "IyEvdXNyL2Jpbi9lbnYgc2gKIwojIFNldHMgdXAgdGhlIGJhc2ljIGFuZCBTU0ggYXV0aGVudGljYXRpb24gYmFzZWQgb24gaW5mb3JtZWQgd29ya3NwYWNlcywgYXMgd2VsbCBhcyBjbGVhbmluZyB1cCB0aGUKIyBwcmV2aW91cyBnaXQtY2xvbmUgc3RhbGUgZGF0YS4KIwoKc2V0IC1ldQoKc291cmNlICQoQ0RQQVRIPSBjZCAtLSAiJChkaXJuYW1lIC0tICR7MH0pIiAmJiBwd2QpL2NvbW1vbi5zaAoKIyMjIyBhc3NlcnRfcmVxdWlyZWRfY29uZmlndXJhdGlvbl9vcl9mYWlsCgpwaGFzZSAiUHJlcGFyaW5nIHRoZSBmaWxlc3lzdGVtIgoKaWYgW1sgIiR7V09SS1NQQUNFU19CQVNJQ19BVVRIX0JPVU5EfSIgPT0gInRydWUiIF1dOyB0aGVuCglwaGFzZSAiQ29uZmlndXJpbmcgR2l0IGF1dGhlbnRpY2F0aW9uIHdpdGggJ2Jhc2ljLWF1dGgnIFdvcmtzcGFjZSBmaWxlcyIKCglmb3IgZiBpbiAuZ2l0LWNyZWRlbnRpYWxzIC5naXRjb25maWc7IGRvCgkJc3JjPSIke1dPUktTUEFDRVNfQkFTSUNfQVVUSF9QQVRIfS8ke2Z9IgoJCXBoYXNlICJDb3B5aW5nICcke3NyY30nIHRvICcke1BBUkFNU19VU0VSX0hPTUV9JyIKCQljb3B5X29yX2ZhaWwgNDAwICR7c3JjfSAiJHtQQVJBTVNfVVNFUl9IT01FfS8iCglkb25lCmZpCgppZiBbWyAiJHtXT1JLU1BBQ0VTX1NTSF9ESVJFQ1RPUllfQk9VTkR9IiA9PSAidHJ1ZSIgXV07IHRoZW4KCXBoYXNlICJDb3B5aW5nICcuc3NoJyBmcm9tIHNzaC1kaXJlY3Rvcnkgd29ya3NwYWNlICgnJHtXT1JLU1BBQ0VTX1NTSF9ESVJFQ1RPUllfUEFUSH0nKSIKCglkb3Rfc3NoPSIke1BBUkFNU19VU0VSX0hPTUV9Ly5zc2giCgljb3B5X29yX2ZhaWwgNzAwICR7V09SS1NQQUNFU19TU0hfRElSRUNUT1JZX1BBVEh9ICR7ZG90X3NzaH0KCWNobW9kIC1SdiA0MDAgJHtkb3Rfc3NofS8qCmZpCgoKZXhpdCAwCg==" |base64 -d >"/scripts/prepare.sh"
        printf '%s' "IyEvdXNyL2Jpbi9lbnYgc2gKCnNob3B0IC1zIGluaGVyaXRfZXJyZXhpdApzZXQgLWV1IC1vIHBpcGVmYWlsCgpzb3VyY2UgJChDRFBBVEg9IGNkIC0tICIkKGRpcm5hbWUgLS0gJHswfSkiICYmIHB3ZCkvY29tbW9uLnNoCgojCiMgSW1hZ2UgaXMgYWxyZWFkeSBjcmVhdGVkCiMgJHtQQVJBTVNfSU1BR0V9CiMKcGhhc2UgInNjcCBpbWFnZSB0byByZW1vdGUgc2VydmVyIgpzY3AgLW8gU3RyaWN0SG9zdEtleUNoZWNraW5nPW5vICR7V09SS1NQQUNFU19JTUFHRURJUkVDVE9SWV9QQVRIfS8ke1BBUkFNU19JTUFHRX0gJHtTU0hfVVNFUn1AJHtTU0hfSE9TVH06JHtTU0hfRElSRUNUT1JZfQoKcGhhc2UgInByZXBhcmUgc2NyaXB0IgpjYXQgPiAke1dPUktTUEFDRVNfSU1BR0VESVJFQ1RPUllfUEFUSH0vZGVwbG95LnNoIDw8RU9GCiMgTm93IHdlIG5lZWVkIHRvIGNyZWF0ZSBhIHNjcmlwdCB0byBleGVjdXRlIHRoZSBpbWFnZQoKIyBDb25maWd1cmFjacOzbiBkZSBwYXLDoW1ldHJvcwpOT0RFUz0ke1BBUkFNU19OT0RFU30gICAgICAgICAgICAgIyBOw7ptZXJvIGRlIG5vZG9zClRBU0tTPSR7UEFSQU1TX1RBU0tTfSAgICAgICAgICAgICAjIE7Dum1lcm8gZGUgdGFyZWFzClBBUlRJVElPTj0iaW50ZXJhY3RpdmUiICAgICAgICAgICAjIE5vbWJyZSBkZSBsYSBwYXJ0aWNpw7NuIC0+IGludGVyYWN0aXZlIChtYXggMiBkw61hcyksIGJhdGNoIChtYXggMzAgZMOtYXMpCldPUktFUj0iJHtQQVJBTVNfV09SS0VSU30iICAgICAgICAjIE5vbWJyZSBkZWwgbm9kbyBkZSB0cmFiYWpvCkdQVVM9JHtQQVJBTVNfR1BVU30gICAgICAgICAgICAgICAjIE7Dum1lcm8gZGUgR1BVcwpKT0JfTkFNRT0iJHtQQVJBTVNfSk9CX05BTUV9IiAgICAgIyBOb21icmUgZGVsIHRyYWJham8KVElNRT0iJHtQQVJBTVNfVElNRX0iICAgICAgICAgICAgICMgTMOtbWl0ZSBkZSB0aWVtcG8gLT4gZS5nLiA0IGTDrWFzIDggaG9yYXMgMDQ6MDg6MDA6MDAKQ09NTUFORD0iJHtQQVJBTVNfQ09NTUFORH0iCgojIEVqZWN1dGFyIGVsIGNvbWFuZG8gc3J1bgpzcnVuIC1LIFwKICAgIC0tY29udGFpbmVyLW1vdW50cz0vaG9tZS8ke1NTSF9VU0VSfTovaG9tZS8ke1NTSF9VU0VSfSBcCiAgICAtLW5vLWNvbnRhaW5lci1yZW1hcC1yb290IFwKICAgIC0tY29udGFpbmVyLXdvcmtkaXI9JChwd2QpIFwKICAgIC0tY29udGFpbmVyLWltYWdlPSIke1NTSF9ESVJFQ1RPUll9LyR7UEFSQU1TX0lNQUdFfSIgXAogICAgLS1udGFza3M9IlwkVEFTS1MiIFwKICAgIC0tbm9kZXM9IlwkTk9ERVMiIFwKICAgIC0tcGFydGl0aW9uICJcJFBBUlRJVElPTiIgXAogICAgLS1ub2RlbGlzdCAiXCRXT1JLRVIiIFwKICAgIC0tZ3B1cz0iXCRHUFVTIiBcCiAgICAtLWpvYi1uYW1lICJcJEpPQl9OQU1FIiBcCiAgICAtLXRpbWUgIlwkVElNRSIgXAogICAgLS1wdHkgL2Jpbi9iYXNoIC1jICJcJHtDT01NQU5EfSIKRU9GCgpwaGFzZSAibWFrZSBzY3JpcHQgZXhlY3V0YWJsZSIKY2htb2QgK3ggJHtXT1JLU1BBQ0VTX0lNQUdFRElSRUNUT1JZX1BBVEh9L2RlcGxveS5zaAoKcGhhc2UgInNjcCBzY3JpcHQgdG8gdGhlcmVtb3RlIHNlcnZlciIKc2NwIC1vIFN0cmljdEhvc3RLZXlDaGVja2luZz1ubyAke1dPUktTUEFDRVNfSU1BR0VESVJFQ1RPUllfUEFUSH0vZGVwbG95LnNoICR7U1NIX1VTRVJ9QCR7U1NIX0hPU1R9OiR7U1NIX0RJUkVDVE9SWX0KCnBoYXNlICJleGVjdXRlIHNjcmlwdCBvbiByZW1vdGUgc2VydmVyIgpzc2ggLW8gU3RyaWN0SG9zdEtleUNoZWNraW5nPW5vICR7U1NIX1VTRVJ9QCR7U1NIX0hPU1R9IFwiY2htb2QgYSt4ICR7U1NIX0RJUkVDVE9SWX0vZGVwbG95LnNoICYmICR7U1NIX0RJUkVDVE9SWX0vZGVwbG95LnNoXCIK" |base64 -d >"/scripts/remote.sh"
        chmod +x /scripts/*.sh
        echo "Running Script /scripts/prepare.sh"
        /scripts/prepare.sh
        echo "Running Script /scripts/remote.sh"
        /scripts/remote.sh
      volumeMounts:
        - mountPath: /scripts
          name: scripts-dir
  volumes:
    - emptyDir: {}
      name: scripts-dir
  workspaces:
    - description: |
        A `.ssh` directory with private key, `known_hosts`, `config`, etc.
        Copied to the user's home, in order to
        server as authentication mechanism binding a Secret to this Workspace is
        strongly recommended over other volume types.
      name: ssh-directory
      optional: true
    - description: |
        A directory for storing the .sqsh image.
      name: imagedirectory
