apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1","kind":"Pipeline","metadata":{"annotations":{},"name":"build-and-deploy","namespace":"pipelines-cpiedraf"},"spec":{"params":[{"description":"name of the deployment to be patched","name":"deployment-name","type":"string"},{"description":"url of the git repo for the code of deployment","name":"git-url","type":"string"},{"default":"master","description":"revision to be used from repo of the code for deployment","name":"git-revision","type":"string"},{"description":"image to be build from the code","name":"IMAGE","type":"string"}],"tasks":[{"name":"fetch-repository","params":[{"name":"URL","value":"$(params.git-url)"},{"name":"SUBDIRECTORY","value":""},{"name":"DELETE_EXISTING","value":"true"},{"name":"REVISION","value":"$(params.git-revision)"}],"taskRef":{"params":[{"name":"kind","value":"task"},{"name":"name","value":"git-clone"},{"name":"namespace","value":"openshift-pipelines"}],"resolver":"cluster"},"workspaces":[{"name":"output","workspace":"shared-workspace"}]},{"name":"build-image","params":[{"name":"IMAGE","value":"$(params.IMAGE)"}],"runAfter":["fetch-repository"],"taskRef":{"params":[{"name":"kind","value":"task"},{"name":"name","value":"buildah"},{"name":"namespace","value":"openshift-pipelines"}],"resolver":"cluster"},"workspaces":[{"name":"source","workspace":"shared-workspace"}]},{"name":"apply-manifests","runAfter":["build-image"],"taskRef":{"name":"apply-manifests"},"workspaces":[{"name":"source","workspace":"shared-workspace"}]},{"name":"update-deployment","params":[{"name":"deployment","value":"$(params.deployment-name)"},{"name":"IMAGE","value":"$(params.IMAGE)"}],"runAfter":["apply-manifests"],"taskRef":{"name":"update-deployment"}}],"workspaces":[{"name":"shared-workspace"}]}}
  name: build-and-deploy
  namespace: pipelines-cpiedraf
spec:
  params:
    - description: name of the deployment to be patched
      name: deployment-name
      type: string
    - description: url of the git repo for the code of deployment
      name: git-url
      type: string
    - default: master
      description: revision to be used from repo of the code for deployment
      name: git-revision
      type: string
    - description: image to be build from the code
      name: IMAGE
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: URL
          value: $(params.git-url)
        - name: SUBDIRECTORY
          value: ''
        - name: DELETE_EXISTING
          value: 'true'
        - name: REVISION
          value: $(params.git-revision)
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build-image
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      runAfter:
        - fetch-repository
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: apply-manifests
      runAfter:
        - build-image
      taskRef:
        kind: Task
        name: apply-manifests
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: update-deployment
      params:
        - name: deployment
          value: $(params.deployment-name)
        - name: IMAGE
          value: $(params.IMAGE)
      runAfter:
        - apply-manifests
      taskRef:
        kind: Task
        name: update-deployment
  workspaces:
    - name: shared-workspace
